[2024-10-11T08:12:32.047+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-11T08:12:32.079+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_yellow_cab.etl_task manual__2024-10-11T07:14:16.194830+00:00 [queued]>
[2024-10-11T08:12:32.083+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_yellow_cab.etl_task manual__2024-10-11T07:14:16.194830+00:00 [queued]>
[2024-10-11T08:12:32.083+0000] {taskinstance.py:2306} INFO - Starting attempt 7 of 7
[2024-10-11T08:12:32.090+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): etl_task> on 2024-10-11 07:14:16.194830+00:00
[2024-10-11T08:12:32.094+0000] {standard_task_runner.py:63} INFO - Started process 201 to run task
[2024-10-11T08:12:32.096+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_yellow_cab', 'etl_task', 'manual__2024-10-11T07:14:16.194830+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/yellow-cab-batch.py', '--cfg-path', '/tmp/tmpd5epwwhs']
[2024-10-11T08:12:32.099+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask etl_task
[2024-10-11T08:12:32.112+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-11T08:12:32.129+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_yellow_cab.etl_task manual__2024-10-11T07:14:16.194830+00:00 [running]> on host yellow-cab-airflow-scheduler
[2024-10-11T08:12:32.172+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hafidz' AIRFLOW_CTX_DAG_ID='etl_yellow_cab' AIRFLOW_CTX_TASK_ID='etl_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-11T07:14:16.194830+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-11T07:14:16.194830+00:00'
[2024-10-11T08:12:32.172+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-11T08:12:32.193+0000] {base.py:84} INFO - Using connection ID 'spark_main' for task execution.
[2024-10-11T08:12:32.195+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.jars.packages=org.apache.sedona:sedona-python-adapter-3.0_2.12:1.2.0-incubating,excludeDependencies=protobuf,org.datasyslab:geotools-wrapper:geotools-24.0,excludeDependencies=protobuf,com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.29.0,com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.2.8,excludeDependencies=protobuf --conf spark.jars.repositories=https://repo1.maven.org/maven2/ --name arrow-spark --deploy-mode client /spark-scripts/taxi_etl.py
[2024-10-11T08:12:33.066+0000] {spark_submit.py:649} INFO - https://repo1.maven.org/maven2/ added as a remote repository with the name: repo-1
[2024-10-11T08:12:33.080+0000] {spark_submit.py:649} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-10-11T08:12:33.106+0000] {spark_submit.py:649} INFO - Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Provided Maven Coordinates must be in the form 'groupId:artifactId:version'. The coordinate provided is: excludeDependencies=protobuf
[2024-10-11T08:12:33.106+0000] {spark_submit.py:649} INFO - at scala.Predef$.require(Predef.scala:281)
[2024-10-11T08:12:33.106+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmitUtils$.$anonfun$extractMavenCoordinates$1(SparkSubmit.scala:1140)
[2024-10-11T08:12:33.106+0000] {spark_submit.py:649} INFO - at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmitUtils$.extractMavenCoordinates(SparkSubmit.scala:1138)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1422)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2024-10-11T08:12:33.107+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-10-11T08:12:33.108+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-10-11T08:12:33.108+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-10-11T08:12:33.115+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-11T08:12:33.122+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 575, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.jars.packages=org.apache.sedona:sedona-python-adapter-3.0_2.12:1.2.0-incubating,excludeDependencies=protobuf,org.datasyslab:geotools-wrapper:geotools-24.0,excludeDependencies=protobuf,com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.29.0,com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.2.8,excludeDependencies=protobuf --conf spark.jars.repositories=https://repo1.maven.org/maven2/ --name arrow-spark --deploy-mode client /spark-scripts/taxi_etl.py. Error code is: 1.
[2024-10-11T08:12:33.123+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_yellow_cab, task_id=etl_task, run_id=manual__2024-10-11T07:14:16.194830+00:00, execution_date=20241011T071416, start_date=20241011T081232, end_date=20241011T081233
[2024-10-11T08:12:33.131+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task etl_task (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.jars.packages=org.apache.sedona:sedona-python-adapter-3.0_2.12:1.2.0-incubating,excludeDependencies=protobuf,org.datasyslab:geotools-wrapper:geotools-24.0,excludeDependencies=protobuf,com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.29.0,com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.2.8,excludeDependencies=protobuf --conf spark.jars.repositories=https://repo1.maven.org/maven2/ --name arrow-spark --deploy-mode client /spark-scripts/taxi_etl.py. Error code is: 1.; 201)
[2024-10-11T08:12:33.138+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-11T08:12:33.145+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-11T08:12:33.146+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
