[2024-10-13T16:34:07.701+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-13T16:34:07.740+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_yellow_cab.geo_create_task manual__2024-10-13T15:26:29.490243+00:00 [queued]>
[2024-10-13T16:34:07.745+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_yellow_cab.geo_create_task manual__2024-10-13T15:26:29.490243+00:00 [queued]>
[2024-10-13T16:34:07.745+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-13T16:34:07.753+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): geo_create_task> on 2024-10-13 15:26:29.490243+00:00
[2024-10-13T16:34:07.757+0000] {standard_task_runner.py:63} INFO - Started process 32959 to run task
[2024-10-13T16:34:07.761+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_yellow_cab', 'geo_create_task', 'manual__2024-10-13T15:26:29.490243+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/yellow-cab-batch.py', '--cfg-path', '/tmp/tmpx8emb1rc']
[2024-10-13T16:34:07.766+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask geo_create_task
[2024-10-13T16:34:07.787+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-13T16:34:07.852+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_yellow_cab.geo_create_task manual__2024-10-13T15:26:29.490243+00:00 [running]> on host yellow-cab-airflow-scheduler
[2024-10-13T16:34:07.935+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hafidz' AIRFLOW_CTX_DAG_ID='etl_yellow_cab' AIRFLOW_CTX_TASK_ID='geo_create_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T15:26:29.490243+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T15:26:29.490243+00:00'
[2024-10-13T16:34:07.936+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-13T16:34:07.958+0000] {base.py:84} INFO - Using connection ID 'spark_main' for task execution.
[2024-10-13T16:34:07.959+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.executor.memory=8g --conf spark.driver.maxResultSize=8g --conf spark.driver.memory=2g --name arrow-spark --deploy-mode client /spark-scripts/taxi_geo_create.py
[2024-10-13T16:34:10.641+0000] {spark_submit.py:649} INFO - Traceback (most recent call last):
[2024-10-13T16:34:10.642+0000] {spark_submit.py:649} INFO - File "/spark-scripts/taxi_geo_create.py", line 31, in <module>
[2024-10-13T16:34:10.642+0000] {spark_submit.py:649} INFO - main()
[2024-10-13T16:34:10.642+0000] {spark_submit.py:649} INFO - File "/spark-scripts/taxi_geo_create.py", line 11, in main
[2024-10-13T16:34:10.642+0000] {spark_submit.py:649} INFO - spark.setLogLevel("WARN")
[2024-10-13T16:34:10.643+0000] {spark_submit.py:649} INFO - AttributeError: 'Builder' object has no attribute 'setLogLevel'
[2024-10-13T16:34:10.703+0000] {spark_submit.py:649} INFO - 24/10/13 16:34:10 INFO ShutdownHookManager: Shutdown hook called
[2024-10-13T16:34:10.704+0000] {spark_submit.py:649} INFO - 24/10/13 16:34:10 INFO ShutdownHookManager: Deleting directory /tmp/spark-42eb6224-fa87-4e75-9ff2-37d53b1302d1
[2024-10-13T16:34:10.742+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-13T16:34:10.749+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 575, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.executor.memory=8g --conf spark.driver.maxResultSize=8g --conf spark.driver.memory=2g --name arrow-spark --deploy-mode client /spark-scripts/taxi_geo_create.py. Error code is: 1.
[2024-10-13T16:34:10.753+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_yellow_cab, task_id=geo_create_task, run_id=manual__2024-10-13T15:26:29.490243+00:00, execution_date=20241013T152629, start_date=20241013T163407, end_date=20241013T163410
[2024-10-13T16:34:10.771+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 84 for task geo_create_task (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.executor.memory=8g --conf spark.driver.maxResultSize=8g --conf spark.driver.memory=2g --name arrow-spark --deploy-mode client /spark-scripts/taxi_geo_create.py. Error code is: 1.; 32959)
[2024-10-13T16:34:10.802+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-13T16:34:10.813+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-13T16:34:10.813+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
